export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const SET_INGREDIENT="SET_INGREDIENT";
export const FETCH_INGREDIENT="FETCH_INGREDIENT";
export const ORDER_SUCCESS="ORDER_SUCCESS";
export const ORDER_FAILURE="ORDER_FAILURE";
export const ORDER_START="ORDER_START";
export const PURCHASE_INIT="PURCHASE_INIT"
export const AUTH_LOGOUT="AUTH_LOGOUT";
export const ORDER_COMPLETE="ORDER_COMPLETE";


